/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Match {
  'id' : string,
  'matchType' : string,
  'startTime' : bigint,
  'status' : string,
  'participants' : Array<Principal>,
  'createdAt' : bigint,
  'entryFee' : number,
}
export interface PaymentSubmission {
  'id' : string,
  'status' : string,
  'user' : Principal,
  'refunded' : boolean,
  'amountPaid' : number,
  'matchId' : string,
  'approved' : boolean,
  'timestamp' : bigint,
  'refundTimestamp' : [] | [bigint],
  'screenshot' : ExternalBlob,
}
export interface UserProfile {
  'refundPaymentQrCode' : ExternalBlob,
  'displayName' : string,
  'email' : string,
  'gamePlayerId' : string,
  'gameName' : string,
  'phoneNumber' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approvePayment' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookAllSlots' : ActorMethod<[string], undefined>,
  'createMatch' : ActorMethod<[string, string, number, bigint], undefined>,
  'getAllMatches' : ActorMethod<[], Array<Match>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMatchDetails' : ActorMethod<[string], [] | [Match]>,
  'getMatchParticipants' : ActorMethod<[string], Array<Principal>>,
  'getMatchesByStatus' : ActorMethod<[string], Array<Match>>,
  'getPaymentStatus' : ActorMethod<[string], [] | [PaymentSubmission]>,
  'getPendingPayments' : ActorMethod<[], Array<PaymentSubmission>>,
  'getUserMatches' : ActorMethod<[], Array<Match>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserRole' : ActorMethod<[], [] | [string]>,
  'getUserTransactionHistory' : ActorMethod<[], Array<PaymentSubmission>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinMatch' : ActorMethod<[string], undefined>,
  'markAsRefunded' : ActorMethod<[string], undefined>,
  'rejectPayment' : ActorMethod<[string], undefined>,
  'removeUser' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitPayment' : ActorMethod<[string, ExternalBlob, number], undefined>,
  'updateUserProfile' : ActorMethod<[Principal, UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];