/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Match = IDL.Record({
  'id' : IDL.Text,
  'matchType' : IDL.Text,
  'startTime' : IDL.Int,
  'status' : IDL.Text,
  'participants' : IDL.Vec(IDL.Principal),
  'createdAt' : IDL.Int,
  'entryFee' : IDL.Float64,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfile = IDL.Record({
  'refundPaymentQrCode' : ExternalBlob,
  'displayName' : IDL.Text,
  'email' : IDL.Text,
  'gamePlayerId' : IDL.Text,
  'gameName' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const PaymentSubmission = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'user' : IDL.Principal,
  'refunded' : IDL.Bool,
  'amountPaid' : IDL.Float64,
  'matchId' : IDL.Text,
  'approved' : IDL.Bool,
  'timestamp' : IDL.Int,
  'refundTimestamp' : IDL.Opt(IDL.Int),
  'screenshot' : ExternalBlob,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approvePayment' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookAllSlots' : IDL.Func([IDL.Text], [], []),
  'createMatch' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64, IDL.Int], [], []),
  'getAllMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMatchDetails' : IDL.Func([IDL.Text], [IDL.Opt(Match)], ['query']),
  'getMatchParticipants' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getMatchesByStatus' : IDL.Func([IDL.Text], [IDL.Vec(Match)], ['query']),
  'getPaymentStatus' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PaymentSubmission)],
      ['query'],
    ),
  'getPendingPayments' : IDL.Func([], [IDL.Vec(PaymentSubmission)], ['query']),
  'getUserMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserRole' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getUserTransactionHistory' : IDL.Func(
      [],
      [IDL.Vec(PaymentSubmission)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinMatch' : IDL.Func([IDL.Text], [], []),
  'markAsRefunded' : IDL.Func([IDL.Text], [], []),
  'rejectPayment' : IDL.Func([IDL.Text], [], []),
  'removeUser' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitPayment' : IDL.Func([IDL.Text, ExternalBlob, IDL.Float64], [], []),
  'updateUserProfile' : IDL.Func([IDL.Principal, UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Match = IDL.Record({
    'id' : IDL.Text,
    'matchType' : IDL.Text,
    'startTime' : IDL.Int,
    'status' : IDL.Text,
    'participants' : IDL.Vec(IDL.Principal),
    'createdAt' : IDL.Int,
    'entryFee' : IDL.Float64,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfile = IDL.Record({
    'refundPaymentQrCode' : ExternalBlob,
    'displayName' : IDL.Text,
    'email' : IDL.Text,
    'gamePlayerId' : IDL.Text,
    'gameName' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const PaymentSubmission = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'user' : IDL.Principal,
    'refunded' : IDL.Bool,
    'amountPaid' : IDL.Float64,
    'matchId' : IDL.Text,
    'approved' : IDL.Bool,
    'timestamp' : IDL.Int,
    'refundTimestamp' : IDL.Opt(IDL.Int),
    'screenshot' : ExternalBlob,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approvePayment' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookAllSlots' : IDL.Func([IDL.Text], [], []),
    'createMatch' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Int],
        [],
        [],
      ),
    'getAllMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMatchDetails' : IDL.Func([IDL.Text], [IDL.Opt(Match)], ['query']),
    'getMatchParticipants' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getMatchesByStatus' : IDL.Func([IDL.Text], [IDL.Vec(Match)], ['query']),
    'getPaymentStatus' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PaymentSubmission)],
        ['query'],
      ),
    'getPendingPayments' : IDL.Func(
        [],
        [IDL.Vec(PaymentSubmission)],
        ['query'],
      ),
    'getUserMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserRole' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getUserTransactionHistory' : IDL.Func(
        [],
        [IDL.Vec(PaymentSubmission)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinMatch' : IDL.Func([IDL.Text], [], []),
    'markAsRefunded' : IDL.Func([IDL.Text], [], []),
    'rejectPayment' : IDL.Func([IDL.Text], [], []),
    'removeUser' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitPayment' : IDL.Func([IDL.Text, ExternalBlob, IDL.Float64], [], []),
    'updateUserProfile' : IDL.Func([IDL.Principal, UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };